name: Lint Documentation Version

on:
  pull_request:
    branches: [ main, master ]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check for version number in markdown
      id: version-check
      run: |
        FILE="Quality Management/Quality Attribute Requirements M1.md"
        if [ ! -f "$FILE" ]; then
          echo "::error file=$FILE::File $FILE does not exist"
          exit 1
        fi
        
        if ! grep -q -E '^#+ \[?[0-9]+\.[0-9]+\.[0-9]+' "$FILE"; then
          echo "::error file=$FILE::No version number found in $FILE. Expected format: '## [x.y.z]' or '# x.y.z'"
          exit 1
        else
          echo "Version number found in $FILE"
        fi
